apiVersion: apps/v1  # The version of the Kubernetes API to use
kind: Deployment  # The kind of Kubernetes resource to create
metadata:
  name: api-td-deployment  # The name of the Deployment resource
  labels:
    app: api-td  # Labels to apply to the Deployment for organization and selection
spec:
  replicas: 1  # The number of replicas (pods) to maintain
  selector:
    matchLabels:
      app: api-td  # The labels to use to select the pods managed by this Deployment
  template:
    metadata:
      labels:
        app: api-td  # Labels to apply to the pods created by this Deployment
    spec:
      containers:
      - name: api-td  # The name of the container to create in each pod
        image: thomasje007/api:latest  # The image to use for the container
        ports:
        - containerPort: 8000  # The port to expose on the container
        env:
        - name: API_URL  # Environment variable to set in the container
          valueFrom:
            configMapKeyRef:
              name: api-td-config  # The name of the ConfigMap from which to get the value
              key: api-url  # The key in the ConfigMap from which to get the value
---
apiVersion: v1  # The version of the Kubernetes API to use
kind: Service  # The kind of Kubernetes resource to create
metadata:
  name: api-td-service  # The name of the Service resource
spec:
  type: NodePort  # The type of Service to create (NodePort exposes the Service on a static port on each Node)
  selector:
    app: api-td  # The labels to use to select the pods to which to route traffic
  ports:
      protocol: TCP  # The protocol to use for the Service
      port: 8000  # The port on which the Service will listen
      targetPort: 8000  # The port on the pods to which to route traffic
      nodePort: 30000  # The port on each Node on which the Service will be exposed