apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-td-deployment
  labels:
    app: api-td
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-td
  template:
    metadata:
      labels:
        app: api-td
    spec:
      containers:
      - name: api-td
        image: thomasje007/api:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-td-service
spec:
  type: NodePort
  selector:
    app: api-td
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
