apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-td-deployment
  labels:
    app: front-td
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-td
  template:
    metadata:
      labels:
        app: front-td
    spec:
      containers:
      - name: front-td
        image: thomasje007/frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-td-service
spec:
  type: NodePort
  selector:
    app: front-td
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
