apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lighttpd-ingress
  namespace: default
spec:
  rules:
    - host: lighttpd.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-td-service
                port:
                  number: 80
    - host: fastapi.local
      http:
        paths:
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: fastapi-service
                port:
                  number: 8000
    - host: fastapi.local
      http:
        paths:
          - path: /changeuser
            pathType: Prefix
            backend:
              service:
                name: fastapi-service
                port:
                  number: 8000