apiVersion: v1  # The version of the Kubernetes API to use
kind: ConfigMap  # The kind of Kubernetes resource to create
metadata:
  name: mongo-td-config  # The name of the ConfigMap resource
data:
  mongo-url: mongo-td-service  # A key-value pair stored in the ConfigMap. This can be used to configure pods.
